#!/usr/bin/env python3
"""Create PowerPoint presentations for TONY realtime automation."""
import json
import os
import sys
from datetime import datetime


def main():
    try:
        payload = json.loads(sys.stdin.read() or "{}")
    except json.JSONDecodeError as e:
        print(json.dumps({"ok": False, "error": str(e)}))
        sys.exit(1)

    title = payload.get("title", "Presentation")
    slides = payload.get("slides") or [{"title": title, "bullets": ["Generated by TONY"]}]

    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        print(json.dumps({
            "ok": False,
            "error": "python-pptx not installed — run: pip install python-pptx",
        }))
        sys.exit(1)

    data_dir = os.environ.get("TONY_DATA_DIR", "./data")
    out_dir = os.path.join(data_dir, "presentations")
    os.makedirs(out_dir, exist_ok=True)

    safe = "".join(c if c.isalnum() or c in " -_" else "_" for c in title)[:60].strip()
    fname = f"{safe}-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.pptx"
    fpath = os.path.join(out_dir, fname)

    prs = Presentation()
    prs.core_properties.title = title

    for i, slide_data in enumerate(slides):
        slide_title = slide_data.get("title", f"Slide {i + 1}")
        bullets = slide_data.get("bullets") or slide_data.get("content") or []

        if i == 0:
            layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = slide_title
            if len(slide.placeholders) > 1 and bullets:
                slide.placeholders[1].text = "\n".join(str(b) for b in bullets[:6])
        else:
            layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = slide_title
            body = slide.shapes.placeholders[1].text_frame
            body.clear()
            for j, bullet in enumerate(bullets[:8]):
                p = body.paragraphs[0] if j == 0 else body.add_paragraph()
                p.text = str(bullet)
                p.level = 0

    prs.save(fpath)
    print(json.dumps({
        "ok": True,
        "path": fpath.replace("\\", "/"),
        "title": title,
        "slideCount": len(slides),
        "note": "Open with PowerPoint or double-click the .pptx file",
    }))


if __name__ == "__main__":
    main()
